# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thwsheji',
            fields=[
                ('podid', models.IntegerField(primary_key=True, serialize=False)),
                ('upid', models.IntegerField()),
                ('quju', models.CharField(max_length=30)),
                ('jiedian', models.CharField(max_length=30)),
                ('jdname', models.CharField(max_length=30)),
                ('sjkyll', models.FloatField()),
                ('sjjdll', models.FloatField()),
                ('sjbf', models.IntegerField()),
                ('sjepgbf', models.IntegerField()),
                ('sjdbkj', models.FloatField()),
                ('opt1', models.CharField(blank=True, db_column='OPT1', max_length=45, null=True)),
                ('opt2', models.CharField(blank=True, db_column='OPT2', max_length=45, null=True)),
                ('opt3', models.CharField(blank=True, db_column='OPT3', max_length=45, null=True)),
                ('opt4', models.CharField(blank=True, db_column='OPT4', max_length=45, null=True)),
                ('opt5', models.CharField(blank=True, db_column='OPT5', max_length=45, null=True)),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
                ('deletetime', models.DateTimeField(blank=True, null=True)),
                ('createowner', models.CharField(blank=True, max_length=30, null=True)),
                ('updateowner', models.CharField(blank=True, max_length=30, null=True)),
                ('deleteowner', models.CharField(blank=True, max_length=30, null=True)),
                ('deleteflag', models.IntegerField()),
            ],
            options={
                'db_table': 'thwsheji',
                'managed': True,
            },
        ),
    ]
