# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tztesheji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=50, unique=True)),
                ('wgname', models.CharField(blank=True, max_length=50, null=True)),
                ('epggroupname', models.CharField(blank=True, max_length=50, null=True)),
                ('sjkyll', models.IntegerField()),
                ('sjjdll', models.IntegerField()),
                ('sjhmsbf', models.IntegerField()),
                ('sjepgbf', models.IntegerField()),
                ('sjdbkj', models.IntegerField()),
                ('nodeid', models.CharField(max_length=50)),
                ('clusterid', models.CharField(max_length=50)),
                ('clustername', models.CharField(max_length=50)),
                ('opt1', models.CharField(blank=True, db_column='OPT1', max_length=45, null=True)),
                ('opt2', models.CharField(blank=True, db_column='OPT2', max_length=45, null=True)),
                ('opt3', models.CharField(blank=True, db_column='OPT3', max_length=45, null=True)),
                ('opt4', models.CharField(blank=True, db_column='OPT4', max_length=45, null=True)),
                ('opt5', models.CharField(blank=True, db_column='OPT5', max_length=45, null=True)),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
                ('deletetime', models.DateTimeField(blank=True, null=True)),
                ('createowner', models.CharField(blank=True, max_length=30, null=True)),
                ('updateowner', models.CharField(blank=True, max_length=30, null=True)),
                ('deleteowner', models.CharField(blank=True, max_length=30, null=True)),
                ('deleteflag', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'tztesheji',
            },
        ),
    ]
